CREATE TABLE `sync_meta` (
	`key` text PRIMARY KEY NOT NULL,
	`value` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
CREATE TABLE `sync_tombstones` (
	`id` text PRIMARY KEY NOT NULL,
	`table_name` text NOT NULL,
	`row_id` text NOT NULL,
	`deleted_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
CREATE UNIQUE INDEX `sync_tombstones_table_row` ON `sync_tombstones` (`table_name`,`row_id`);--> statement-breakpoint
CREATE INDEX `sync_tombstones_deleted` ON `sync_tombstones` (`deleted_at`);--> statement-breakpoint
CREATE TRIGGER trg_sync_students AFTER DELETE ON students BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'students', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_study_groups AFTER DELETE ON study_groups BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'study_groups', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_student_groups AFTER DELETE ON student_groups BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'student_groups', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_group_sessions AFTER DELETE ON group_sessions BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'group_sessions', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_session_exceptions AFTER DELETE ON session_exceptions BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'session_exceptions', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_attendance AFTER DELETE ON attendance BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'attendance', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_session_attendance AFTER DELETE ON session_attendance BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'session_attendance', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_plans AFTER DELETE ON plans BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'plans', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_payments AFTER DELETE ON payments BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'payments', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_expenses AFTER DELETE ON expenses BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'expenses', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_homeworks AFTER DELETE ON homeworks BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'homeworks', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_homework_submissions AFTER DELETE ON homework_submissions BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'homework_submissions', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_exams AFTER DELETE ON exams BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'exams', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_exam_results AFTER DELETE ON exam_results BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'exam_results', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_skills AFTER DELETE ON skills BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'skills', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_student_skills AFTER DELETE ON student_skills BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'student_skills', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;--> statement-breakpoint
CREATE TRIGGER trg_sync_weak_points AFTER DELETE ON weak_points BEGIN INSERT INTO sync_tombstones (id, table_name, row_id, deleted_at, created_at, updated_at) VALUES (lower(hex(randomblob(16))), 'weak_points', OLD.id, (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000), (CAST(strftime('%s','now') AS INTEGER) * 1000)); END;
